name: Post to Notion

on:
  workflow_dispatch:  # 手動実行のみ

concurrency:
  group: post-to-notion
  cancel-in-progress: true  # 連打しても同時実行しない

permissions:
  contents: read

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install notion-client

      - name: Run post script
        working-directory: eichoga_poster
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: python post.py
